apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: http
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: agent
      protocol: UDP
      port: 6831
      targetPort: 6831
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.26
        ports:
        - containerPort: 16686
        - containerPort: 6831
