apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: divyak1107/finalver-login:1.0
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SERVICE_NAME
              value: login
          ports:
            - containerPort: 5000
